"""
Type stub file for pyroute2 library.

This file provides minimal type hints for the pyroute2 library used in the project.
Only includes the IPRoute class that is imported in can.py.
"""

from typing import Any, overload

# Custom NetlinkMessage type that includes get_attr method
class NetlinkMessage(dict[str, Any]):
    """Represents a Netlink message, provides get_attr method."""

    def get_attr(self, attr_name: str) -> Any: ...

class IPRoute:
    """Basic interface to RTNL."""

    def __init__(self) -> None: ...
    @overload
    def get_links(self) -> list[NetlinkMessage]: ...
    @overload
    def get_links(self, *args: Any, **kwargs: Any) -> list[NetlinkMessage]: ...
    def get_links(self, *args: Any, **kwargs: Any) -> list[NetlinkMessage]: ...
    def link(self, command: str, *args: Any, **kwargs: Any) -> Any: ...
    def close(self) -> None: ...
    def __enter__(self) -> IPRoute: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
