from typing import Any

class Document:
    page_content: str
    metadata: dict[str, Any]

    def __init__(self, page_content: str, metadata: dict[str, Any]) -> None: ...

class FAISS:
    @staticmethod
    def from_documents(documents: list[Document], embedding: Any) -> FAISS: ...
    @staticmethod
    def load_local(folder_path: str, embeddings: Any) -> FAISS: ...
    def save_local(self, folder_path: str) -> None: ...
    def similarity_search(self, query: str, k: int = 4) -> list[Document]: ...
